export const attendance = [
  {
    id: "80123098",
    name: "Anderson Dark",
    avatar: "/placeholder.svg?height=32&width=32",
    position: "General Manager",
    date: "24 July 2024",
    checkIn: "10:00 AM",
    checkOut: "06:00 PM",
    stayTime: "08 Hours",
    status: "Check Out",
  },
  {
    id: "80123066",
    name: "White Elefant",
    avatar: "/placeholder.svg?height=32&width=32",
    position: "Room Cleaner",
    date: "22 July 2024",
    checkIn: "02:00 PM",
    checkOut: null,
    stayTime: "03 Hours",
    status: "Working On",
  },
  {
    id: "80123056",
    name: "Mark Ganson",
    avatar: "/placeholder.svg?height=32&width=32",
    position: "Front Desk",
    date: "21 March 2022",
    checkIn: "02:00 PM",
    checkOut: "10:00 PM",
    stayTime: "08 Hours",
    status: "Check Out",
  },
  {
    id: "80123041",
    name: "Sugar Soil",
    avatar: "/placeholder.svg?height=32&width=32",
    position: "Designer",
    date: "20 July 2024",
    checkIn: "03:00 PM",
    checkOut: null,
    stayTime: "06 Hours",
    status: "Working On",
  },
]

