export const maintenance = [
  {
    roomNo: "102",
    workType: "AC Change",
    priority: "High",
    makerAssign: [
      { name: "John", avatar: "/placeholder.svg?height=32&width=32" },
      { name: "Sarah", avatar: "/placeholder.svg?height=32&width=32" },
    ],
    costMaintenance: 1020,
    status: "Working On",
    note: "AC Buy From Haeaj",
  },
  {
    roomNo: "104",
    workType: "Washroom Water Bell",
    priority: "Low",
    makerAssign: [{ name: "Mike", avatar: "/placeholder.svg?height=32&width=32" }],
    costMaintenance: 15520,
    status: "Pending",
    note: "Quick work needed",
  },
  {
    roomNo: "105",
    workType: "Telephone Broke",
    priority: "High",
    makerAssign: [
      { name: "Emma", avatar: "/placeholder.svg?height=32&width=32" },
      { name: "James", avatar: "/placeholder.svg?height=32&width=32" },
    ],
    costMaintenance: 1520,
    status: "Pending",
    note: "Jarir Book Store",
  },
  {
    roomNo: "108",
    workType: "Bed Set Broke",
    priority: "Low",
    makerAssign: [
      { name: "Lisa", avatar: "/placeholder.svg?height=32&width=32" },
      { name: "Tom", avatar: "/placeholder.svg?height=32&width=32" },
    ],
    costMaintenance: 9123,
    status: "Finish Work",
    note: "Buy From Ikea Store",
  },
  {
    roomNo: "206",
    workType: "Table Change",
    priority: "High",
    makerAssign: [
      { name: "Alex", avatar: "/placeholder.svg?height=32&width=32" },
      { name: "Maria", avatar: "/placeholder.svg?height=32&width=32" },
    ],
    costMaintenance: 100,
    status: "Working On",
    note: "Quick work needed",
  },
  {
    roomNo: "205",
    workType: "AC Modify",
    priority: "High",
    makerAssign: [
      { name: "John", avatar: "/placeholder.svg?height=32&width=32" },
      { name: "David", avatar: "/placeholder.svg?height=32&width=32" },
    ],
    costMaintenance: 500,
    status: "Pending",
    note: "Quick work needed",
  },
  {
    roomNo: "201",
    workType: "Chair Change",
    priority: "Low",
    makerAssign: [{ name: "Sarah", avatar: "/placeholder.svg?height=32&width=32" }],
    costMaintenance: 19120,
    status: "Working On",
    note: "Quick work needed",
  },
  {
    roomNo: "306",
    workType: "AC Change",
    priority: "High",
    makerAssign: [{ name: "Mike", avatar: "/placeholder.svg?height=32&width=32" }],
    costMaintenance: 10520,
    status: "Working On",
    note: "AC Buy From Haeaj",
  },
  {
    roomNo: "801",
    workType: "Bed Set Change",
    priority: "High",
    makerAssign: [
      { name: "Emma", avatar: "/placeholder.svg?height=32&width=32" },
      { name: "James", avatar: "/placeholder.svg?height=32&width=32" },
    ],
    costMaintenance: 188,
    status: "Pending",
    note: "Buy From Ikea Store",
  },
  {
    roomNo: "1010",
    workType: "Handale Change",
    priority: "High",
    makerAssign: [
      { name: "John", avatar: "/placeholder.svg?height=32&width=32" },
      { name: "Sarah", avatar: "/placeholder.svg?height=32&width=32" },
    ],
    costMaintenance: 1520,
    status: "Working On",
    note: "Quick work needed",
  },
]

