export const promotions = [
  {
    name: "Target Audience Rate",
    discountType: "Up to 50% Off",
    startDate: "02 July 2024",
    endDate: "Always Active",
    grossBooking: "12,665",
    averageRate: 30,
    grossRevenue: "15,000",
    status: "Active Now",
  },
  {
    name: "New Hotel Deal",
    discountType: "Up to 70% Off",
    startDate: "08 July 2024",
    endDate: "20 October 2024",
    grossBooking: "18,665",
    averageRate: 40,
    grossRevenue: "45,000",
    status: "Active Now",
  },
  {
    name: "Deals with Package",
    discountType: "Cupon Code",
    startDate: "10 July 2024",
    endDate: "20 July 2024",
    grossBooking: "12,665",
    averageRate: 30,
    grossRevenue: "25,000",
    status: "Ending Soon",
  },
  {
    name: "New Property Deal",
    discountType: "Up to 70% Off",
    startDate: "20 July 2024",
    endDate: "Always Active",
    grossBooking: "12,665",
    averageRate: 90,
    grossRevenue: "20,000",
    status: "Active Now",
  },
  {
    name: "New Hotels Deal",
    discountType: "Cash Back",
    startDate: "25 June 2024",
    endDate: "25 July 2024",
    grossBooking: "12,665",
    averageRate: 30,
    grossRevenue: "15,000",
    status: "Ending Soon",
  },
  {
    name: "Target Audience Rate",
    discountType: "Cupon Code",
    startDate: "27 July 2024",
    endDate: "Always Active",
    grossBooking: "12,665",
    averageRate: 10,
    grossRevenue: "10,000",
    status: "Active Now",
  },
  {
    name: "New Property Deal",
    discountType: "Up to 70% Off",
    startDate: "29 July 2024",
    endDate: "Always Active",
    grossBooking: "12,665",
    averageRate: 5,
    grossRevenue: "95,000",
    status: "Active Now",
  },
]

