import { guests } from "./data";

export const reviews = [
  {
    id: 1,
    name: "Raiders Kae",
    avatar: guests[0].avatar,
    totalSpent: 2967.0,
    date: "20/12/2024",
    rating: 4.9,
    text: "I was really let down by my stay at this hotel. The room was nothing like I expected – it felt old, wasn't cleaned well, and had this weird smell that just wouldn't go away.\n\nThe air conditioning barely did its job, so it was pretty uncomfortable, and the noise from the other rooms and outside kept me awake most of the night.",
    replied: false,
  },
  {
    id: 2,
    name: "Jassy Mac",
    avatar: guests[1].avatar,
    totalSpent: 2239.0,
    date: "19/12/2024",
    rating: 4.4,
    text: "The room was nothing like I expected - it felt old, wasn't cleaned well, and had this weird smell that just wouldn't go away.\n\nThe service was disappointing and the amenities were not up to the standard I expected for the price.",
    replied: true,
  },
  {
    id: 3,
    name: "Macculam Brad",
    avatar: guests[2].avatar,
    totalSpent: 3766.0,
    date: "18/12/2024",
    rating: 4.4,
    text: "The air conditioning barely did its job, so it was pretty uncomfortable. The room temperature was inconsistent and made it difficult to sleep.\n\nOn the positive side, the staff was friendly and tried their best to help with the situation.",
    replied: false,
  },
  {
    id: 4,
    name: "Jhoney Cark",
    avatar: guests[3].avatar,
    totalSpent: 5644.0,
    date: "17/12/2024",
    rating: 4.4,
    text: "It felt old, wasn't cleaned well, and had this weird smell that just wouldn't go away. The bathroom facilities need serious updating.\n\nThe location was good, but that's about the only positive thing I can say.",
    replied: true,
  },
  {
    id: 5,
    name: "Jhon Brak",
    avatar: guests[4].avatar,
    totalSpent: 5443.0,
    date: "16/12/2024",
    rating: 4.1,
    text: "Nothing like I expected - it felt old, wasn't cleaned well, and the amenities were lacking. The WiFi was extremely slow and unreliable.\n\nBreakfast was average at best, with limited options for dietary restrictions.",
    replied: false,
  },
  {
    id: 6,
    name: "Rod Atone",
    avatar: guests[0].avatar,
    totalSpent: 5799.0,
    date: "15/12/2024",
    rating: 3.9,
    text: "I was really let down by my stay at this hotel. The room service was slow, and the food quality was inconsistent.\n\nThe gym equipment was outdated and some machines were out of order during my entire stay.",
    replied: false,
  },
  {
    id: 7,
    name: "Sade Repideo",
    avatar: guests[2].avatar,
    totalSpent: 527.0,
    date: "13/12/2024",
    rating: 3.9,
    text: "Room was nothing like I expected - it felt old, wasn't cleaned properly, and the furniture showed significant wear and tear.\n\nThe walls were thin, and I could hear everything from the neighboring rooms.",
    replied: false,
  },
]

