export const staff = [
  {
    id: "#80123098",
    name: "Anderson Dark",
    avatar: "/placeholder.svg?height=32&width=32",
    position: "General Manager",
    hireDate: "24 July 2024",
    agreement: "2 Years",
    hireType: "Salary",
    salaryRate: "1500.00",
    status: "Active Staff",
  },
  {
    id: "#80123066",
    name: "White Elefant",
    avatar: "/placeholder.svg?height=32&width=32",
    position: "Room Cleaner",
    hireDate: "22 July 2024",
    agreement: "4 Years",
    hireType: "Contact",
    salaryRate: "1000.00",
    status: "Active Staff",
  },
  {
    id: "#80123056",
    name: "Mark Ganson",
    avatar: "/placeholder.svg?height=32&width=32",
    position: "Front Desk",
    hireDate: "21 March 2022",
    agreement: "6 Years",
    hireType: "Salary",
    salaryRate: "500.00",
    status: "Pending Staff",
  },
  {
    id: "#80123041",
    name: "Sugar Soil",
    avatar: "/placeholder.svg?height=32&width=32",
    position: "Designer",
    hireDate: "20 July 2024",
    agreement: "2 Month",
    hireType: "Hourly",
    salaryRate: "1000.00",
    status: "Active Staff",
  },
  {
    id: "#80123040",
    name: "Criss Brak",
    avatar: "/placeholder.svg?height=32&width=32",
    position: "Marketing Manager",
    hireDate: "17 July 2024",
    agreement: "9 Month",
    hireType: "Salary",
    salaryRate: "3000.00",
    status: "Active Staff",
  },
  {
    id: "#80123030",
    name: "Lionel Messi",
    avatar: "/placeholder.svg?height=32&width=32",
    position: "Cleaner Staff",
    hireDate: "16 July 2024",
    agreement: "12 Month",
    hireType: "Intern",
    salaryRate: "1200.00",
    status: "Pending Staff",
  },
  {
    id: "#80123028",
    name: "Ronaldo Praso",
    avatar: "/placeholder.svg?height=32&width=32",
    position: "Room Cleaner",
    hireDate: "15 July 2024",
    agreement: "2 Years",
    hireType: "Salary",
    salaryRate: "1000.00",
    status: "Active Staff",
  },
]

