import { IdType, VisitorType, type VisitorInfo } from "@/types/visitor"

export const visitors: VisitorInfo[] = [
  {
    id: "V001",
    type: VisitorType.GUEST,
    firstName: "John",
    lastName: "Doe",
    idType: IdType.PASSPORT,
    idNumber: "P123456789",
    email: "john@example.com",
    phone: "1234567890",
    checkInTime: "2024-02-19T09:00:00",
    checkOutTime: null,
    apartmentNumber: "A101",
    residentName: "Alice Smith",
    luggage: [
      {
        id: "L1",
        description: "Black suitcase",
        checkedOut: false,
      },
      {
        id: "L2",
        description: "Laptop bag",
        checkedOut: false,
      },
    ],
  },
  {
    id: "V002",
    type: VisitorType.MAINTENANCE,
    firstName: "Mike",
    lastName: "Johnson",
    idType: IdType.NATIONAL_ID,
    idNumber: "ID98765432",
    email: "mike@repair.com",
    phone: "9876543210",
    checkInTime: "2024-02-19T08:30:00",
    checkOutTime: "2024-02-19T11:45:00",
    workOrderNumber: "WO123",
    description: "AC Repair in Unit B204",
    luggage: [
      {
        id: "L3",
        description: "Toolbox",
        checkedOut: true,
      },
    ],
  },
  {
    id: "V003",
    type: VisitorType.DELIVERY,
    firstName: "Sarah",
    lastName: "Wilson",
    idType: IdType.DRIVING_LICENSE,
    idNumber: "DL456789",
    email: "sarah@delivery.com",
    phone: "5554443333",
    checkInTime: "2024-02-19T10:15:00",
    checkOutTime: null,
    trackingNumber: "TN789",
    apartmentNumber: "C303",
  },
  {
    id: "V004",
    type: VisitorType.TOUR,
    firstName: "Emma",
    lastName: "Brown",
    idType: IdType.PASSPORT,
    idNumber: "P987654321",
    email: "emma@example.com",
    phone: "7778889999",
    checkInTime: "2024-02-19T14:00:00",
    checkOutTime: null,
    appointmentId: "APT456",
  },
]

